# Generated by cucumber-sinatra. (2014-12-17 12:09:17 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/github_badges.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = GithubBadges

class GithubBadgesWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  GithubBadgesWorld.new
end
