# Generated by cucumber-sinatra. (2014-12-17 12:09:17 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/issue_counter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = IssueCounter

class IssueCounterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  IssueCounterWorld.new
end
